In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 13.2 ms, sys: 12.5 ms, total: 25.7 ms
Wall time: 28.8 ms


In [2]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 559 ms, sys: 153 ms, total: 712 ms
Wall time: 728 ms


In [3]:
data = np.random.randn(2, 3)
data

array([[-0.32421199,  1.11349554,  0.18006886],
       [-1.93075784,  1.13927468, -0.81393742]])

In [4]:
data*10

array([[ -3.24211989,  11.1349554 ,   1.80068857],
       [-19.30757843,  11.39274681,  -8.13937425]])

In [5]:
data + data

array([[-0.64842398,  2.22699108,  0.36013771],
       [-3.86151569,  2.27854936, -1.62787485]])

In [6]:
data.shape
data.dtype

dtype('float64')

In [7]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)

In [8]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [11]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int64')

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.empty((2, 3, 2))

array([[[2.00000000e+000, 2.00000000e+000],
        [2.96439388e-323, 0.00000000e+000],
        [8.48798316e-313, 1.61590357e+184]],

       [[6.80896078e-091, 9.50811943e-043],
        [1.56088031e+184, 3.11181144e-032],
        [3.99910963e+252, 8.38736309e-309]]])

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [21]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [22]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [23]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [24]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [25]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [27]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50],dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [28]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [29]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [30]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [31]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [34]:
arr ** 0.5


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [35]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [37]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [38]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[5]

5

In [40]:
arr[5:8]

array([5, 6, 7])

In [41]:
arr[5:8] = 12

In [42]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [43]:
arr_slice = arr[5:8]

In [44]:
arr_slice

array([12, 12, 12])

In [45]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [46]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [47]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [51]:
x[0]

array([7, 8, 9])

In [52]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [53]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [54]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [57]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [58]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [59]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [60]:
data

array([[-0.41279904,  1.38424709, -0.8641951 ,  0.76891314],
       [-1.98614467, -0.92842891,  1.995913  , -0.56502905],
       [-1.08998637,  0.59154327,  0.36744961,  0.63829496],
       [ 1.81943629,  1.73865099,  0.6749853 ,  1.11552655],
       [ 1.12185752,  0.11158351,  0.99907641, -0.87188548],
       [-0.00577754, -1.68005712,  0.49462946,  1.64134282],
       [ 0.47045295,  1.90576278,  1.60092444, -0.07902151]])

In [64]:
names == 'Joe'

False

In [65]:
data[names == 'Bob']

array([[[-0.41279904,  1.38424709, -0.8641951 ,  0.76891314],
        [-1.98614467, -0.92842891,  1.995913  , -0.56502905],
        [-1.08998637,  0.59154327,  0.36744961,  0.63829496],
        [ 1.81943629,  1.73865099,  0.6749853 ,  1.11552655],
        [ 1.12185752,  0.11158351,  0.99907641, -0.87188548],
        [-0.00577754, -1.68005712,  0.49462946,  1.64134282],
        [ 0.47045295,  1.90576278,  1.60092444, -0.07902151]]])

In [66]:
data[names == 'Joe']

array([], shape=(0, 7, 4), dtype=float64)

In [67]:
names != 'Bob'

False

In [68]:
names == 'Bob'

True

In [70]:
names == 'Bob'

True

In [71]:
mask = (names == 'Bob') | (names == 'Will')

In [72]:
mask

True

In [74]:
data[mask]

array([[[-0.41279904,  1.38424709, -0.8641951 ,  0.76891314],
        [-1.98614467, -0.92842891,  1.995913  , -0.56502905],
        [-1.08998637,  0.59154327,  0.36744961,  0.63829496],
        [ 1.81943629,  1.73865099,  0.6749853 ,  1.11552655],
        [ 1.12185752,  0.11158351,  0.99907641, -0.87188548],
        [-0.00577754, -1.68005712,  0.49462946,  1.64134282],
        [ 0.47045295,  1.90576278,  1.60092444, -0.07902151]]])

In [75]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [76]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [77]:
arr = np.arange(15).reshape((3, 5))

In [78]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [79]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [80]:
arr = np.random.randn(6, 3)

In [81]:
arr

array([[-0.4469484 , -1.06611433,  0.17232994],
       [-0.20742781,  1.51966353,  0.27431659],
       [ 0.46369662, -1.03957189,  0.65431286],
       [ 0.92952996, -1.30482515,  1.03380688],
       [ 1.32449015, -0.28330087,  0.60515362],
       [-1.65831819, -1.07313965,  0.05231722]])

In [82]:
np.dot(arr.T, arr)

array([[ 5.82612303, -0.12926464,  1.84519506],
       [-0.12926464,  7.46114347, -2.02358121],
       [ 1.84519506, -2.02358121,  1.97077718]])

In [84]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [86]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [87]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [88]:
arr.swapaxes(1, 2)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [89]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [91]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [92]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([ 0.20807091,  0.92571547,  0.00260043, -0.25177714, -0.19728366,
        0.59637426, -1.22330626, -0.33095691])

In [93]:
y

array([-1.05394288,  1.14286161,  1.02042239,  1.48837008, -0.28940268,
       -0.53459029,  0.31187124, -1.69277418])

In [94]:
np.maximum(x,y)

array([ 0.20807091,  1.14286161,  1.02042239,  1.48837008, -0.19728366,
        0.59637426,  0.31187124, -0.33095691])

In [95]:
arr = np.random.randn(7) * 5
arr

array([ 9.59654166,  2.42889306, -3.73890662,  4.11359388,  3.47534839,
        4.28652701,  2.40030667])

In [96]:
reminder,whole_part = np.modf(arr)
reminder

array([ 0.59654166,  0.42889306, -0.73890662,  0.11359388,  0.47534839,
        0.28652701,  0.40030667])

In [97]:
whole_part

array([ 9.,  2., -3.,  4.,  3.,  4.,  2.])

# numpy100题

In [98]:
import numpy as np

In [99]:
print(np.__version__)
np.show_config()

1.15.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [100]:
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [101]:
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [102]:
print("%d bytes" % (Z.size * Z.itemsize))

80 bytes


In [103]:
Y = np.zeros((10,10))
Y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [104]:
print("%d bytes"%(Y.size * Y.itemsize))

800 bytes


In [105]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [109]:
Z = np.zeros(10)
Z[2] = 1
print(Z)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


In [110]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [111]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [114]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [115]:
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4]),)

In [116]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [117]:
Z = np.random.random((10,10))
Zmin,Zmax = Z.min(),Z.max
print(Zmin,Zmax)

0.0014920463469364487 <built-in method max of numpy.ndarray object at 0x11ad4e6c0>


In [118]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.85979024 0.1389472  0.16847574]
  [0.02927308 0.00259928 0.49015845]
  [0.27222601 0.58487949 0.83914413]]

 [[0.74480377 0.17200691 0.7925477 ]
  [0.5098107  0.38744695 0.63423335]
  [0.38431322 0.45528854 0.75798667]]

 [[0.53428013 0.79897392 0.16642603]
  [0.77008536 0.96545441 0.83546279]
  [0.0060217  0.30829831 0.87679853]]]


In [120]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5445286941560262


In [121]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [124]:
Z = np.ones((5,5))
Z = np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [125]:
print(0 * np.nan)

nan


In [126]:
print(np.nan == np.nan)

False


In [127]:
print(np.inf > np.nan)

False


In [128]:
print(np.nan - np.nan)

nan


In [129]:
print(0.3 == 3 * 0.1)

False


In [130]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [131]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [134]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [135]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [136]:
np.random.random((5,5))
Zmax,Zmin = Z.max(),Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [137]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [138]:
Z = np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [140]:
Z = np.arange(11)
Z[(3 < Z & (Z <= 8))] *= -1
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [141]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [142]:
print(np.array(0) / np.array(0))

nan


/Users/running/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [143]:
print(np.array(0) // np.array(0))

0


/Users/running/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [144]:
Z = np.random.uniform(-10.+10.10)
print(Z)

0.7843130046039639


In [145]:
print (np.copysign(np.ceil(np.abs(Z)), Z))

1.0


In [146]:
z1 = np.random.randint(0,10,10)
print(z1)

[5 7 6 0 2 8 6 5 4 4]


In [148]:
z2 = np.random.randint(0,10,10)
print(np.intersectld(z1,z2))

AttributeError: module 'numpy' has no attribute 'intersectld'

In [149]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-06
Today is 2019-08-07
Tomorrow is 2019-08-08


In [150]:
z = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [155]:
a = np.ones(3)*1
b = np.ones(3)*2
c = np.ones(3)*3
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)

array([-1.5, -1.5, -1.5])

In [156]:
z = np.random.uniform(0,10,10)
print(z)

[3.4449033  1.95237168 3.06343511 7.96052827 1.1385623  9.75966344
 8.6706439  9.28895182 6.48123813 8.15372318]


In [157]:
print(np.trunc(z))

[3. 1. 3. 7. 1. 9. 8. 9. 6. 8.]


In [158]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [160]:
def generate():
     for x in range(10):
         yield x
 Z = np.fromiter(generate(),dtype=float,count=-1)
 print (Z)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 4)

In [161]:
 def generate():
     for x in range(10):
         yield x
 Z = np.fromiter(generate(),dtype=float,count=-1)
 print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [162]:
z = np.linspace(0,1,11,endpoint=False)[1:]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [163]:
z = np.random.random(10)
z.sort()
print(z)

[0.09787594 0.23629287 0.2570209  0.40932498 0.54254336 0.74836343
 0.75190814 0.83967767 0.92773294 0.95917347]


In [164]:
z = arange(10)
np.add.reduce(z)

45

In [165]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [166]:
Z = np.random.random(10)
print(Z)

[0.35016971 0.72498621 0.74768486 0.33341737 0.65115308 0.82573625
 0.87499132 0.89249524 0.9614306  0.57774955]


In [168]:
Z.argmax()

8

In [170]:
Z[Z.argmax()] = 0
print(Z)

[0.35016971 0.72498621 0.74768486 0.33341737 0.65115308 0.82573625
 0.87499132 0.89249524 0.         0.57774955]


In [171]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                              np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [172]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [173]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)    
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [174]:
for dtype in [np.float32, np.float64]:
     print(np.finfo(dtype).min)
     print(np.finfo(dtype).max)
     print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [175]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [176]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

91


In [177]:
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [180]:
print(v)

90.91336856348265
