In [1]:
import pandas as pd
import numpy as np
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [2]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [3]:
string_data[0] = None
string_data.isnull()#判断缺失值

0     True
1    False
2     True
3    False
dtype: bool

In [4]:
from numpy import nan as NA
data = pd.Series([1,NA,3.5,NA,7])

In [5]:
data.dropna()#去除缺失值

0    1.0
2    3.5
4    7.0
dtype: float64

In [6]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
   ....:                      [NA, NA, NA], [NA, 6.5, 3.]])

In [8]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [9]:
cleaned = data.dropna()#dropna会将dataframe中含有缺失值的整行整列删除

In [10]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [11]:
data.dropna(how='all')#传入how=‘all’将只丢弃权威NA的值

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [12]:
data[4] = NA

In [13]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [14]:
data.dropna(axis = 1,how = 'all')#传入axis = 1将只删除列

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [15]:
df = pd.DataFrame(np.random.randn(7,3))
df.iloc[:4,1] = NA
df.iloc[:2,2] = NA
df

0         1         2
0 -0.681037       NaN       NaN
1  0.620024       NaN       NaN
2  1.551650       NaN -0.296597
3 -0.370414       NaN -1.646464
4  0.383946 -1.040111  0.172245
5  1.800049  1.812319 -1.518270
6  0.831362 -0.909857 -1.426501

In [16]:
df.dropna()

0         1         2
4  0.383946 -1.040111  0.172245
5  1.800049  1.812319 -1.518270
6  0.831362 -0.909857 -1.426501

In [17]:
df.dropna(thresh = 2)

0         1         2
2  1.551650       NaN -0.296597
3 -0.370414       NaN -1.646464
4  0.383946 -1.040111  0.172245
5  1.800049  1.812319 -1.518270
6  0.831362 -0.909857 -1.426501

In [18]:
df.fillna(0)

0         1         2
0 -0.681037  0.000000  0.000000
1  0.620024  0.000000  0.000000
2  1.551650  0.000000 -0.296597
3 -0.370414  0.000000 -1.646464
4  0.383946 -1.040111  0.172245
5  1.800049  1.812319 -1.518270
6  0.831362 -0.909857 -1.426501

In [19]:
df.fillna({1:0.5,2:0})

0         1         2
0 -0.681037  0.500000  0.000000
1  0.620024  0.500000  0.000000
2  1.551650  0.500000 -0.296597
3 -0.370414  0.500000 -1.646464
4  0.383946 -1.040111  0.172245
5  1.800049  1.812319 -1.518270
6  0.831362 -0.909857 -1.426501

In [20]:
df

0         1         2
0 -0.681037       NaN       NaN
1  0.620024       NaN       NaN
2  1.551650       NaN -0.296597
3 -0.370414       NaN -1.646464
4  0.383946 -1.040111  0.172245
5  1.800049  1.812319 -1.518270
6  0.831362 -0.909857 -1.426501

In [21]:
_ = df.fillna(0,inplace=True)
df

0         1         2
0 -0.681037  0.000000  0.000000
1  0.620024  0.000000  0.000000
2  1.551650  0.000000 -0.296597
3 -0.370414  0.000000 -1.646464
4  0.383946 -1.040111  0.172245
5  1.800049  1.812319 -1.518270
6  0.831362 -0.909857 -1.426501

In [22]:
df = pd.DataFrame(np.random.randn(6,3))

In [23]:
df

0         1         2
0 -0.190640  2.524908 -0.514101
1  3.061673 -0.204115  0.272832
2  0.204800  0.516277 -0.144514
3 -0.208972  0.422068  0.099231
4 -0.551041 -0.736194  1.751409
5 -0.197790 -0.059512 -1.643080

In [24]:
df.iloc[2:,1] = NA
df.iloc[4:,2] = NA
df

0         1         2
0 -0.190640  2.524908 -0.514101
1  3.061673 -0.204115  0.272832
2  0.204800       NaN -0.144514
3 -0.208972       NaN  0.099231
4 -0.551041       NaN       NaN
5 -0.197790       NaN       NaN

In [25]:
df.fillna(method='ffill')

0         1         2
0 -0.190640  2.524908 -0.514101
1  3.061673 -0.204115  0.272832
2  0.204800 -0.204115 -0.144514
3 -0.208972 -0.204115  0.099231
4 -0.551041 -0.204115  0.099231
5 -0.197790 -0.204115  0.099231

In [26]:
df.fillna(method='ffill',limit=2)

0         1         2
0 -0.190640  2.524908 -0.514101
1  3.061673 -0.204115  0.272832
2  0.204800 -0.204115 -0.144514
3 -0.208972 -0.204115  0.099231
4 -0.551041       NaN  0.099231
5 -0.197790       NaN  0.099231

In [27]:
data = pd.Series([1.,NA,3.5,NA,7])

In [28]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [29]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
   ....:                      'k2': [1, 1, 2, 3, 3, 4, 4]})

In [30]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [31]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [32]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [33]:
data['v1'] = range(7)

In [34]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [35]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [36]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
   ....:                               'Pastrami', 'corned beef', 'Bacon',
   ....:                               'pastrami', 'honey ham', 'nova lox'],
   ....:                      'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [37]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [38]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}

In [39]:
lowercased = data['food'].str.lower()

In [40]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [41]:
data['animal'] = lowercased.map(meat_to_animal)#Series的map方法可以接受一个函数或含有映射关系的字典型对象

In [42]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [43]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [44]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [45]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [46]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [47]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [48]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [49]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
   ....:                     index=['Ohio', 'Colorado', 'New York'],
   ....:                     columns=['one', 'two', 'three', 'four'])

In [50]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [51]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

In [52]:
cats = pd.cut(ages, bins)#面元划分，以后面的区间划分

In [53]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [54]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [55]:
cats.categories#展示划分的面元

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [56]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [57]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [58]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [59]:
pd.cut(ages,bins,labels = group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [60]:
data = np.random.rand(20)
data

array([0.41675001, 0.90741642, 0.6435451 , 0.21507201, 0.16276277,
       0.74062215, 0.66148666, 0.26772864, 0.60918683, 0.35592009,
       0.52541004, 0.91942721, 0.79899556, 0.2958428 , 0.99721501,
       0.0830159 , 0.3944996 , 0.27916826, 0.29315226, 0.29605702])

In [61]:
pd.cut(data, 4, precision=2)#分成四组，小数点后保留2位

[(0.31, 0.54], (0.77, 1.0], (0.54, 0.77], (0.082, 0.31], (0.082, 0.31], ..., (0.082, 0.31], (0.31, 0.54], (0.082, 0.31], (0.082, 0.31], (0.082, 0.31]]
Length: 20
Categories (4, interval[float64]): [(0.082, 0.31] < (0.31, 0.54] < (0.54, 0.77] < (0.77, 1.0]]

In [62]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [63]:
data

0         1         2         3
0   -0.078572 -0.871105 -0.200473 -1.203687
1    0.038178 -1.819480  0.586306 -1.620953
2   -0.824835  0.755733 -0.558725  0.338649
3    0.379288  0.029481  0.414411 -0.274641
4   -0.369071  0.057625  0.727840  0.700099
..        ...       ...       ...       ...
995  0.127619 -0.553123 -0.699365 -0.541409
996  0.003015 -0.547048  0.725177 -1.598683
997  0.426587  0.234284 -0.998573 -0.031752
998 -0.377505  1.194933  0.403665 -0.784757
999 -0.978881 -1.138991 -0.832997 -1.199990

[1000 rows x 4 columns]

In [64]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.000734    -0.002785    -0.010666    -0.057077
std       1.001825     0.993852     0.990477     1.013827
min      -2.930226    -2.840518    -3.291260    -2.830798
25%      -0.658610    -0.670795    -0.697137    -0.757106
50%      -0.006248     0.014233     0.012669    -0.059111
75%       0.681944     0.705358     0.628459     0.629471
max       3.142930     2.743498     3.027167     3.272540

In [65]:
col = data[2]

In [66]:
col[np.abs(col)>3]

360    3.027167
414    3.014705
881   -3.291260
980   -3.264750
Name: 2, dtype: float64

In [67]:
data[(np.abs(data) > 3).any(1)]#any可以将绝对值大于3的正数和负数都筛选出来

0         1         2         3
18   3.142930  0.501440  1.172059 -0.193715
309 -0.628731  0.350072 -1.526312  3.272540
330  3.136068  1.564044 -1.274519  0.268095
360  0.016642 -0.338022  3.027167 -1.251689
414 -1.234927  0.944794  3.014705  0.091600
881 -0.692216 -1.693198 -3.291260  1.876365
980  0.069350 -0.010214 -3.264750  0.855272

In [68]:
data[np.abs(data) > 3] = np.sign(data) * 3#根据数据的值是正还是负，np.sign(data)可以生成1和-1：

In [69]:
np.sign(data).head

<bound method NDFrame.head of        0    1    2    3
0   -1.0 -1.0 -1.0 -1.0
1    1.0 -1.0  1.0 -1.0
2   -1.0  1.0 -1.0  1.0
3    1.0  1.0  1.0 -1.0
4   -1.0  1.0  1.0  1.0
..   ...  ...  ...  ...
995  1.0 -1.0 -1.0 -1.0
996  1.0 -1.0  1.0 -1.0
997  1.0  1.0 -1.0 -1.0
998 -1.0  1.0  1.0 -1.0
999 -1.0 -1.0 -1.0 -1.0

[1000 rows x 4 columns]>

In [70]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [71]:
sampler = np.random.permutation(5)

In [72]:
sampler

array([4, 0, 2, 1, 3])

In [73]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [74]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
0   0   1   2   3
2   8   9  10  11
1   4   5   6   7
3  12  13  14  15

In [75]:
df.sample(n=3)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11

In [76]:
choices = pd.Series([5, 7, -1, 6, 4])

In [77]:
draws = choices.sample(n=10, replace=True)

In [78]:
draws

2   -1
2   -1
3    6
0    5
2   -1
3    6
3    6
0    5
4    4
2   -1
dtype: int64

In [80]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
   .....:                    'data1': range(6)})

In [81]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [82]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [83]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [84]:
df_with_dummy = df[['data1']].join(dummies)

In [85]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [86]:
val = 'a,b,  guido'

In [87]:
val.split(',')

['a', 'b', '  guido']

In [88]:
pieces = [x.strip() for x in val.split(',')]

In [89]:
pieces

['a', 'b', 'guido']

In [90]:
first, second, third = pieces

In [91]:
first + '::' + second + '::' + third

'a::b::guido'

In [92]:
'guido' in val

True

In [93]:
val.index(',')

1

In [94]:
val.find(':')

-1

In [95]:
val.count(',')

2

In [96]:
val.replace(',', '::')

'a::b::  guido'

In [97]:
val.replace(',', '')

'ab  guido'